title: Kurt's Proxmox Server Setup Docs
description: A fake description 
theme: just-the-docs

url: https://kurtshuler.github.io/proxmox-setup-docs/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
